import { useState } from 'react'
import Image from 'next/image'
import Head from 'next/head'

import { NodeModal } from '../src/NodeModal/NodeModal'
import styles from '../styles/Home.module.scss'

export default function Home() {
  const [elem, setElem] = useState<HTMLElement>(null)

  return (
    <div className={styles.container}>
      <Head>
        <title>Skoppig</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div
          onClick={ev => setElem(ev.target as HTMLElement)}
          style={{
            width: '60px',
            height: '60px',
            backgroundColor: 'blue'
          }}
        >
          Get menu
        </div>
        <NodeModal elem={elem} close={() => setElem(null)} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
